cStoreMVC.UI/Controllers/AuthorsADOController.cs
using cStore.Domain.Models;
using cStoreMVC.Data.ADO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cStoreMVC.UI.Controllers
{
    public class AuthorsADOController : Controller
    {

        AuthorsDAL authors = new AuthorsDAL();




        // GET: AuthorsADO
        public ActionResult Index()
        {
            ViewBag.firstnames = authors.GetFirstnames();
            return View();
        }

        public ActionResult GetAuthors()
        {
            return View(authors.GetAuthors());
        }

        public ActionResult CreateAuthor()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAuthor(AuthorModel author)
        {
            if (ModelState.IsValid)
            {


                authors.CreateAuthor(author);
                return RedirectToAction("GetAuthors");
            }
            return View(author);

        }

        public ActionResult UpdateAuthor(int id)
        {
            return View(authors.GetAuthor(id));
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateAuthor(AuthorModel author)
        {
            if (ModelState.IsValid)
            {
                authors.Updateauthor(author);
                return RedirectToAction("GetAuthors");

            }
            return View(author);
        }

        public ActionResult DeleteAuthor(int id)
        {
            authors.DeleteAuthor(id);
            return RedirectToAction("GetAuthors");
        }

    }
}

cStoreMVC.UI/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cStoreMVC.Data.EF;
using cStore.Domain.repositories;
using cStore.Domain;

namespace cStoreMVC.UI.Controllers
{
    public class GenresController : Controller
    {
        //private cStoreEntities db = new cStoreEntities();
        //GenreRepository repo = new GenreRepository();
        UnitOfWork uow = new UnitOfWork();
        // GET: Genres
        public ActionResult Index()
        {
            return View(uow.GenreRepository.Get());
        }

        // GET: Genres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = uow.GenreRepository.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // GET: Genres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GenreID,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                uow.GenreRepository.Add(genre);
                uow.Save();
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        // GET: Genres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = uow.GenreRepository.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GenreID,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                uow.GenreRepository.Update(genre);
                uow.Save();
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = uow.GenreRepository.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }
            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Genre genre = uow.GenreRepository.Find(id);
            uow.GenreRepository.Remove(genre);
            uow.Save();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

cStoreMVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title | buhlockay</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css">
    <link href="~/Content/Styles/main.css" rel="stylesheet">
    <link href="~/Content/Styles/responsive.css" rel="stylesheet">

    <link rel="shortcut icon" href="Content/Images/Ico/favicon.ico">
</head><!--/head-->
<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="tel:+01-913-322-7000"><i class="fa fa-phone"></i> 913-322-7000</a></li>
                                <li><a href="mailto:info@centriqcstore.com"><i class="fa fa-envelope"></i> info@centriqcstore.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="https://www.facebook.com/CentriqTraining/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://twitter.com/CentriqTraining" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/centriq-foss-training" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/user/CentriqTraining" target="_blank"><i class="fa fa-youtube"></i></a></li>
                                <li><a href="#https://plus.google.com/108553092060324883743" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="index.html"><span>Centriq</span> cStore</a>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <!-- Unauthenticated -->
                                <li id="cart-button">
                                    <a href="#"><i class="fa fa-shopping-cart"></i> Cart</a>
                                    <span id="cart-notification" class="notification-counter"></span>
                                </li>
                                <li><a href="#"><i class="fa fa-user"></i> Register</a></li>
                                <li><a href="#"><i class="fa fa-lock"></i> Login</a></li>

                                <!-- Authenticated -->
                                <!--
                                <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                                <li><a href="#"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                                <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                                <li><a href="#"><i class="fa fa-lock"></i> Logout</a></li>
                                -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="navbar"class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="@Url.Action("Index","Home")">Home</a></li>
                                <li><a href="@Url.Action("FAQ","Home")">FAQ</a></li>
                                <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                                <li><a href="@Url.Action("GetAuthors","AuthorsADO")">authors</a></li>
                                <li><a href="@Url.Action("CreateAuthor","AuthorsADO")">Create author</a></li>
                                <li><a href="@Url.Action("GetPublishers","PublishersADO")">pubs</a></li>
                                <li><a href="@Url.Action("Index","Genres")">Genres</a></li>
                                



                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->
    <div class="text-center alert alert-danger">
        @ViewBag.ErrorMessage
    </div>
    @RenderBody()



    <footer id="footer">
        <!--footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p>Copyright &copy; 2017 Centriq cStore. All rights reserved</p>
                    <p> This application has served @System.Web.HttpContext.Current.Application["totalUsers"] users since the application started.</p>
                </div>
            </div>
        </div>
    </footer><!--/footer-->

    <div id="dialog" title="Shopping Cart">
        <p id="cart-contents">
            Your cart is currently empty
        </p>
    </div>

    <div id="adminLink" onclick="openNav()" class="button">
        <span class="vertical-text">ADMIN</span>
    </div>
    <div id="adminSideNav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="#">User Admin</a>
        <a href="#">Roles Admin</a>
        <a href="#">Manage Titles</a>
        
        <a href="#">Manage Authors</a>
        <@Html.ActionLink("Cafe?", "Cafe", "Home");
    </div>


    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        $(function () {
            $('#navbar li').each(function () {
                if ($(this).find('a').attr('href') == window.location.pathname) {
                    $(this).addClass('current');
                }
            })
        });
    </script>

    @RenderSection("scripts", false)

</body>
</html>




@***********OLD SHIT**********888*@


@*
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>@ViewBag.Title - My ASP.NET Application</title>
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")

        </head>
        <body>
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </footer>
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </body>
    </html>
*@