cStoreMVC.UI/Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cStoreMVC.Data.EF;
using cStore.Domain.repositories;
using cStore.Domain;
using LinqKit;

namespace cStoreMVC.UI.Controllers
{
    public class TitlesController : Controller
    {
        //private cStoreEntities db = new cStoreEntities();
        //TitleRepository repo = new TitleRepository();
        UnitOfWork uow = new UnitOfWork();
        //create repository instancese for DropDownList Population
        //PublisherRepository repoP = new PublisherRepository();

        //GenreRepository repoG = new GenreRepository();

            //Search implemented in IGenericRepo and Generic repo
            public ActionResult Search()
        {
            return View();
        }

        //process the search results
        //parameters define the fields searchable and the ones marked join give us the ands/ors in the where
        public ActionResult SearchResults(string bookTitle, string joinPubDate, string startPubDate,string endPubDate, string joinDescription,
            string description, string joinPrice, decimal? price)
        {
            //create var that builds our linq expression
            var predicate = PredicateBuilder.New<Title>();

            //evaluate and handle the values passed in thru the Action.
            if (!string.IsNullOrEmpty(bookTitle))
            {
                predicate = predicate.And(e => e.BookTitle.Contains(bookTitle));
            }

            //these are created so that if tryparse fails we dont end up with object reference not set to an instance
            DateTime startDateRange = new DateTime();
            DateTime endDateRange = new DateTime();

            //attempt to parse the date time out is what to use if failure to parse occurs
            if (DateTime.TryParse(startPubDate, out startDateRange) &&(DateTime.TryParse(endPubDate, out endDateRange)))
            {
                //by the value of join add and/or to our search query
                if (joinPubDate == "and")
                {
                    predicate = predicate.And(e => e.PublishDate.Value >= startDateRange && e.PublishDate.Value <= endDateRange);

                }
                else
                {
                    predicate = predicate.Or(e => e.PublishDate.Value >= startDateRange && e.PublishDate.Value <= endDateRange);
                }
            }

            if (!string.IsNullOrEmpty(joinDescription))
            {
                if (joinDescription =="and")
                {
                    predicate = predicate.And(e => e.Description.Contains(description));
                }
                else
                {
                    predicate = predicate.Or(e => e.Description.Contains(description));

                }
            }
            if (price !=null)
            {
                if (joinPrice == "and")
                {
                    predicate = predicate.And(e => e.Price.Value <= price);

                }
                else
                {
                    predicate = predicate.Or(e => e.Price.Value >= price);
                }
            }

            //return the results after compiling the query and executing via the repository
            return View(uow.TitleRepository.Search(predicate).OrderBy(m => m.BookTitle));

        }



        // GET: Titles
        public ActionResult Index()
        {
            //var titles = db.Titles.Include(t => t.Genre).Include(t => t.Publisher);
            //this is why we have the for each in the generic repo
            return View(uow.TitleRepository.Get("Genre, Publisher"));
            //this result is the same as the linq statement above witht he includes

        }

        // GET: Titles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = uow.TitleRepository.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // GET: Titles/Create
        public ActionResult Create()
        {

            //create instaces of the genre repository and the publishers repository so that thaey can be used as a data source for the dropdown lists
            //see the top of the class for those declarations.

            //this is the id called by the view to populate the ddl
            ViewBag.GenreID = 
                //create a new ddl ([querythat returns the table represented]
                new SelectList(uow.GenreRepository.Get(),
                //[Value],[displaytext]
                "GenreID", "GenreName");
            ViewBag.PublisherID = new SelectList(uow.PublisherRepository.Get(), "PublisherID", "PublisherName");
            return View();
        }

        // POST: Titles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TitleID,ISBN,BookTitle,Description,GenreID,Price,UnitsSold,PublishDate,PublisherID,BookImage,IsSiteFeature,IsGenreFeature,IsEBook")] Title title)
        {
            if (ModelState.IsValid)
            {
                uow.TitleRepository.Add(title);
                uow.Save();
                    return RedirectToAction("Index");
            }

            ViewBag.GenreID = new SelectList(uow.GenreRepository.Get(), "GenreID", "GenreName", title.GenreID);
            ViewBag.PublisherID = new SelectList(uow.PublisherRepository.Get(), "PublisherID", "PublisherName", title.PublisherID);
            return View(title);
        }

        // GET: Titles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = uow.TitleRepository.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenreID = new SelectList(uow.GenreRepository.Get(), "GenreID", "GenreName", title.GenreID);
            ViewBag.PublisherID = new SelectList(uow.PublisherRepository.Get(), "PublisherID", "PublisherName", title.PublisherID);
            return View(title);
        }

        // POST: Titles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TitleID,ISBN,BookTitle,Description,GenreID,Price,UnitsSold,PublishDate,PublisherID,BookImage,IsSiteFeature,IsGenreFeature,IsEBook")] Title title)
        {
            if (ModelState.IsValid)
            {
                uow.TitleRepository.Update(title);
                uow.Save();
                    return RedirectToAction("Index");
            }
            ViewBag.GenreID = new SelectList(uow.GenreRepository.Get(), "GenreID", "GenreName", title.GenreID);
            ViewBag.PublisherID = new SelectList(uow.PublisherRepository.Get(), "PublisherID", "PublisherName", title.PublisherID);
            return View(title);
        }

        // GET: Titles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Title title = uow.TitleRepository.Find(id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }

        // POST: Titles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Title title = uow.TitleRepository.Find(id);
            uow.TitleRepository.Remove(title);
            uow.Save();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

cStoreMVC.UI/Views/Titles/Create.cshtml
@model cStoreMVC.Data.EF.Title

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsSold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsSold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsSold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherID, "PublisherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PublisherID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PublisherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSiteFeature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSiteFeature)
                    @Html.ValidationMessageFor(model => model.IsSiteFeature, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsGenreFeature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsGenreFeature)
                    @Html.ValidationMessageFor(model => model.IsGenreFeature, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsEBook, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsEBook)
                    @Html.ValidationMessageFor(model => model.IsEBook, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

cStoreMVC.UI/Views/Titles/Delete.cshtml
@model cStoreMVC.Data.EF.Title

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitsSold)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitsSold)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSiteFeature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSiteFeature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsGenreFeature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsGenreFeature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsEBook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEBook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher.PublisherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

cStoreMVC.UI/Views/Titles/Details.cshtml
@model cStoreMVC.Data.EF.Title

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ISBN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitsSold)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitsSold)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSiteFeature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSiteFeature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsGenreFeature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsGenreFeature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsEBook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEBook)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher.PublisherName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TitleID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

cStoreMVC.UI/Views/Titles/Edit.cshtml
@model cStoreMVC.Data.EF.Title

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TitleID)

        <div class="form-group">
            @Html.LabelFor(model => model.ISBN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ISBN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ISBN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsSold, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsSold, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsSold, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherID, "PublisherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PublisherID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PublisherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSiteFeature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSiteFeature)
                    @Html.ValidationMessageFor(model => model.IsSiteFeature, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsGenreFeature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsGenreFeature)
                    @Html.ValidationMessageFor(model => model.IsGenreFeature, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsEBook, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsEBook)
                    @Html.ValidationMessageFor(model => model.IsEBook, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

cStoreMVC.UI/Views/Titles/Search.cshtml
@model cStoreMVC.Data.EF.Title

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>


@*change the default behacior of BeginForm() and send our data to searchresults() in the controller for processing and sind it using
    Get - users can bookmark the results*@
@using (Html.BeginForm("SearchResults","Titles",FormMethod.Get)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Title</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

        <div class="form-group">
            @Html.LabelFor(model => model.BookTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookTitle, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.BookTitle, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select name="joinDescription">
                    <option value="and">AND</option>
                    <option value="or">OR</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select name="joinPrice">
                    <option value="and">AND</option>
                    <option value="or">OR</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Price Below</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select name="joinPubDate">
                    <option value="and">AND</option>
                    <option value="or">OR</option>
                </select>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jQueryval")

cStoreMVC.UI/Views/Titles/SearchResults.cshtml
@model IEnumerable<cStoreMVC.Data.EF.Title>

@{
    ViewBag.Title = "Search Results";
}

<h2>Search Results</h2>
@if (Model.Count()==0)
{
    <h2>the item searched was not found. please return and change your search criteria<br /></h2>    
    @Html.ActionLink("return to search","Search", "Titles")
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PublishDate)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.BookTitle)*@
            @Html.ActionLink(item.BookTitle, "Details", new { @id = item.TitleID})
        </td>
        <td><img src="@Url.Content("~/content/images/books/" + item.BookImage)" title="@item.BookImage"/></td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PublishDate)
        </td>
    </tr>
}

</table>